#!/bin/sh
### BEGIN INIT INFO
# Provides:          BLE-Scanner
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This file starts the Loxberry BLE-Scanner Plugin Daemon.
# Description:       This file starts the Loxberry BLE-Scanner Plugin Daemon.
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin:REPLACELBHOMEDIR/bin"
PATH=$PATH.":REPLACELBHOMEDIR/sbin"

. /lib/lsb/init-functions

### END INIT INFO

# Version v2018.2.28
# 28.02.2018 23:00:40

logfile="REPLACELBPLOGDIR/BLE-Scanner.log"
touch $logfile
chown loxberry:loxberry $logfile

case "${1:-''}" in
  'stop')
        pkill -f "/usr/bin/php -f REPLACELBPHTMLAUTHDIR/bin/daemon.php"
        if [ $? -eq 1 ]
        then
          # Exit with Status 1
          log_failure_msg "BLE-Scanner daemon not running"
        else
          log_daemon_msg "BLE-Scanner daemon stopped" "OK"
          log_end_msg 0
        fi
        exit 0
        ;;
  'status')
        output=$( pgrep -f "/usr/bin/php -f REPLACELBPHTMLAUTHDIR/bin/daemon.php" )
        if [ $? -eq 1 ]
        then
          log_action_msg "Not running"
        else
          log_action_msg "Running with PID `echo -n $output`"
        fi
        exit 0
        ;;
    *)
        output=$( pgrep -f "/usr/bin/php -f REPLACELBPHTMLAUTHDIR/bin/daemon.php" )
        if [ $? -eq 1 ]
        then
          if [ -r /etc/rsyslog.d/99-BLE-Scanner.conf ]
          then
            echo "`date` - Update remove syslog errors rule but not restarting syslog"                                       >>$logfile 2>&1
            log_daemon_msg "Update remove syslog errors rule but not restarting syslog" "OK\n"
            echo ':msg,contains,"advertising data length corrected" ~' > /etc/rsyslog.d/99-BLE-Scanner.conf
            echo ':msg,contains,"bt_err_ratelimited:" ~'              >> /etc/rsyslog.d/99-BLE-Scanner.conf
          else
            echo "`date` - Create remove syslog errors rule + restart syslog"                                                >>$logfile 2>&1
            log_daemon_msg "Create remove syslog errors rule + restart syslog" "OK\n"
            echo ':msg,contains,"advertising data length corrected" ~' > /etc/rsyslog.d/99-BLE-Scanner.conf
            echo ':msg,contains,"bt_err_ratelimited:" ~'              >> /etc/rsyslog.d/99-BLE-Scanner.conf
            service rsyslog restart                                                                                          >>$logfile 2>&1
          fi
          echo "`date` - Restart Bluetooth... "                                                                              >>$logfile 2>&1
          systemctl stop  hciuart.service                                                                                    >>$logfile 2>&1
          systemctl start hciuart.service                                                                                    >>$logfile 2>&1
          if [ $? -eq 1 ]
          then
            systemctl status hciuart.service                                                                                 >>$logfile 2>&1
            echo "`date` - Error during start of hciuart service - try again"                                                >>$logfile 2>&1
            systemctl stop hciuart.service                                                                                   >>$logfile 2>&1
            systemctl start hciuart.service                                                                                  >>$logfile 2>&1
            if [ $? -eq 1 ]
            then
              systemctl status hciuart.service                                                                               >>$logfile 2>&1
              echo "`date` - Error during 2nd start of hciuart service - try again "                                         >>$logfile 2>&1
              systemctl stop hciuart.service                                                                                 >>$logfile 2>&1
              systemctl start hciuart.service                                                                                >>$logfile 2>&1
              if [ $? -eq 1 ]
              then
                systemctl status hciuart.service                                                                             >>$logfile 2>&1
                echo "`date` - Error during 3rd start of hciuart service - giving up"                                        >>$logfile 2>&1
                log_failure_msg "Error during start of bluetooth interface hci0 - please check"
                exit 1
              fi
            fi
          fi
          echo "`date` - Successful start of hciuart service"                                                                >>$logfile 2>&1
          systemctl status hciuart.service                                                                                   >>$logfile 2>&1
          # Start daemon
          log_action_msg "Try to start BLE-Scanner daemon"
          # Now start the daemon
            if [ -x /bin/hciconfig ]
            then
              /bin/hciconfig hci0 up                                                                                         >>$logfile 2>&1
              if [ $? -eq 1 ]
              then
                echo "`date` - Error during start of bluetooth interface hci0 - retry "                                      >>$logfile 2>&1
                /bin/hciconfig hci0 up                                                                                       >>$logfile 2>&1
                if [ $? -eq 1 ]
                then
                echo "`date` - Error during 2nd start of bluetooth interface hci0 - retry "                                  >>$logfile 2>&1
                  log_failure_msg "Error during 2nd start of bluetooth interface hci0 - please check"
                  exit 1
                fi
              fi
              if [ -x /usr/bin/php ]
              then
                if [ -x /usr/bin/python ]
                then
                  output=$( /usr/bin/php -f REPLACELBPHTMLAUTHDIR/bin/daemon.php >/dev/null 2>&1 & )
                  output=$( pgrep -f "/usr/bin/php -f REPLACELBPHTMLAUTHDIR/bin/daemon.php" )
                  if [ $? -eq 1 ]
                  then
                    echo "`date` - BLE-Scanner Daemon NOT started"                                                           >>$logfile 2>&1
                    log_failure_msg "BLE-Scanner Daemon NOT started"
                    exit 1
                  else
                    echo "`date` - BLE-Scanner Daemon started"                                                               >>$logfile 2>&1
                    log_daemon_msg "BLE-Scanner Daemon started" "OK"
                    log_end_msg 0
                    exit 0
                  fi
                 else
                    echo "`date` - Python not found"                                                                         >>$logfile 2>&1
                  log_failure_msg "Python not found"
                  exit 1
                 fi
              else
                echo "`date` - PHP not found"                                                                                >>$logfile 2>&1
                log_failure_msg "PHP not found"
                exit 1
              fi
            else
                echo "`date` - Starting Bluetooth interface using 'hciconfig' failed"                                        >>$logfile 2>&1
              log_failure_msg "Starting Bluetooth interface using 'hciconfig' failed"
              exit 1
            fi
        else
          echo "`date` - Error: BLE-Scanner PHP-Daemon already running with PID `echo -n $output` - please use stop first"   >>$logfile 2>&1
          log_failure_msg "BLE-Scanner PHP-Daemon already running with PID `echo -n $output` - please use stop first"
          exit 1
        fi
        exit 1
        ;;
esac
